# Generated by Django 5.1 on 2025-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='English Level')),
                ('title', models.CharField(max_length=100, verbose_name='Grammar title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Topic Status')),
            ],
        ),
    ]
