# Generated by Django 5.1 on 2024-08-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcontent', '0003_alter_englishcontent_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishcontent',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='English Level'),
        ),
    ]
