# Generated by Django 5.1 on 2024-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcontent', '0004_alter_englishcontent_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='englishcontent',
            old_name='grammar_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='englishcontent',
            name='grammar_theory',
        ),
        migrations.AddField(
            model_name='englishcontent',
            name='theory',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
