# Generated by Django 5.1 on 2024-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcontent', '0005_rename_grammar_title_englishcontent_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishcontent',
            name='theory',
        ),
        migrations.AddField(
            model_name='englishcontent',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
