# Generated by Django 5.1 on 2024-08-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcontent', '0006_remove_englishcontent_theory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcontent',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Topic Status'),
        ),
    ]
