# Generated by Django 5.1 on 2024-08-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='Country')),
                ('english_level', models.CharField(blank=True, max_length=2, null=True, verbose_name='English Level')),
                ('plan_subscribed', models.CharField(blank=True, max_length=1, null=True, verbose_name='Plan Subscribed')),
                ('plan_status', models.BooleanField(default=False, verbose_name='Plan Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
