# Generated by Django 5.1 on 2024-08-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcontent', '0002_alter_englishcontent_level'),
        ('users', '0002_userprofile_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='english_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='englishcontent.englishcontent'),
            preserve_default=False,
        ),
    ]
