# Generated by Django 5.1 on 2024-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_english_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='english_level',
            field=models.CharField(max_length=2, verbose_name='English Level'),
        ),
    ]
