# Generated by Django 5.1 on 2024-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_subscribed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Plan Subscribed'),
        ),
    ]
