# Generated by Django 5.1 on 2024-08-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_english_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_of_user',
            field=models.CharField(default=1, max_length=7, verbose_name='Type of user'),
            preserve_default=False,
        ),
    ]
