# Generated by Django 5.1 on 2024-08-24 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15, verbose_name='name')),
                ('last_name', models.TextField(max_length=15, verbose_name='last name')),
                ('email', models.TextField(max_length=30, verbose_name='email')),
                ('phone_number', models.TextField(max_length=15, verbose_name='phone number')),
                ('country', models.TextField(max_length=15, verbose_name='country')),
                ('english_level', models.TextField(max_length=2, verbose_name='english level')),
                ('plan_subscribed', models.CharField(max_length=1, verbose_name='plan subscribed')),
                ('plan_status', models.BooleanField(default=False, verbose_name='plan status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
