# Generated by Django 5.1 on 2024-08-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('englishcontent', '0007_englishcontent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='A1Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_levels', models.OneToOneField(limit_choices_to={'level': 'A1', 'topic_status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='A1_content', to='englishcontent.englishcontent')),
            ],
        ),
    ]
