# Generated by Django 5.1 on 2024-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a1content',
            name='english_levels',
        ),
        migrations.AddField(
            model_name='a1content',
            name='pdf_files',
            field=models.FileField(default=1, upload_to='pdfs/', verbose_name='PDF File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='a1content',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Topic Title'),
            preserve_default=False,
        ),
    ]
